### ISSUE TITLE
Does a point belong to a polygon function

### ISSUE THREAD

**Issue by wildsurfer** [luizbarboza/shapefile#1]
I’m building a Flutter app that needs to analyse location(lat, lon) and tell if this location is a water or a land. I want it to work offline that’s why I’m planning to embed a shapefile with the coastline polygons. File can be taken here: https://osmdata.openstreetmap.de/data/water-polygons.html (Simplified polygons).

Is there a method in your library that can be used to do what I want?

Thanks for your work, @SBanksX!

**Comment by luizbarboza** [comment]
@wildsurfer You can use this package to convert to GeoJSON format.

To check if the point is contained in a set of polygons that represent the land, just use the [geoContains](https://pub.dev/documentation/d4_geo/latest/d4_geo/geoContains.html) function from the [d4_geo](https://github.com/SBanksX/d4_geo) package.
