### ISSUE TITLE
Can't read geometries from the file (stream is empty)

### ISSUE THREAD

**Issue by wildsurfer** [luizbarboza/shapefile#2]
I'm trying to read geometries from the OSM maps shapefile. Stream is always empty. Shapefile attached (downloaded here: https://osmdata.openstreetmap.de/data/water-polygons.html)

```dart
      final stream = shapefile.geometries(
        File("assets/osm-shapefile/simplified_water_polygons.shp").openRead(),
      );

      stream.map((feature) {
        print(feature); // this code block never reached
      });
```

[simplified-water-polygons-split-3857.zip](https://github.com/SBanksX/shapefile/files/11068393/simplified-water-polygons-split-3857.zip)

@SBanksX

**Comment by luizbarboza** [comment]
@wildsurfer The ```map``` method just returns a new stream, it doesn't iterate through the stream.

Try using the ```forEach``` method instead.
